"""empty message

Revision ID: ddf003fceb77
Revises: fdb8b754a9aa
Create Date: 2023-02-25 20:15:29.575465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf003fceb77'
down_revision = 'fdb8b754a9aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uquser_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uquser_username'), ['username'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uquser_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uquser_email'), type_='unique')

    # ### end Alembic commands ###
